### ISSUE TITLE
Set specific version tag lumigo-injector image as default in Helm chart

### ISSUE THREAD

**Issue by mmanciop** [lumigo-io/lumigo-kubernetes-operator#17]
Every time a new tag (except for `latest`) is released for the injector image, use it to update the default in the Helm chart and publish a new Helm chart release.

**Comment by AkshayAwate** [comment]
Hi, @mmanciop before implementing want to discuss about the solution, can we keep `tag: ""`
```
injectorWebhook:
  lumigoInjector:
    image:
      repository: public.ecr.aws/lumigo/lumigo-autotrace
      tag: ""
```
whenever user wants to deploy with particular version they can pass as `tag: "1.0.0"` else `latest` tag will be used. i have tried with using `tag: "1.0.0"`, image was able to pick tag like this: 
`      LUMIGO_INJECTOR_IMAGE:         public.ecr.aws/lumigo/lumigo-autotrace:1.0.0`, should i make changes and raise PR ?
